version: "3"

services:
  express:
    container_name: express
    restart: always
    build: .
    ports:
      - "${EXPRESS_PORT}:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"